### ISSUE TITLE
Wall torches have "missing asset" texture and drop nothing when broken

### ISSUE THREAD

**Issue by enduum** [vini2003/Bamboo-Tweaks#15] opened 2021-04-25 02:51 UTC
Title. Applies to both green and dry variants. Ground torches seem fine. Tested on a clean instance with no other mods aside from dependencies.

[[Video]](https://youtu.be/jYV-IwpERlc)

Minecraft 1.16.5
Fabric Loader 0.11.3
Fabric API 0.33.0
Fabric Language Kotlin 1.5.0
Architectury 1.12.145
Bamboo Tweaks 2.0.5

**Comment by K0-RR** [comment] 2021-04-30 19:58
Probably a duplicate of my #12 but your title explains what's wrong better.

**Comment by irunatbullets** [comment] 2021-05-07 09:17
Dried bamboo torches placed on barrels do this in AOF3 2.7.2. When placed on dirt and sand they're fine though.

![2021-05-07_11 12 28](https://user-images.githubusercontent.com/344908/117427892-c7764600-af25-11eb-9757-dce75578b952.png)

**Comment by vini2003** [comment] 2021-11-14 14:25
Fixed in release `3.0.0`.

**Closed as completed by vini2003** 2021-11-14 14:25 UTC
Labels: bug
